name: Generate ascii flow

on:
  push:
    paths:
      - 'ascii-script.sh'
      - '.github/workflows/ascii.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manually running'
        required: false
        default: ''

jobs:
  build_job1:
    runs-on: ubuntu-latest 
    steps:
      - name:  Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ® Install cowsay
        run: |
          echo "::group::ğŸ® Installing cowsay"
          sudo apt-get install -y cowsay
          echo "::endgroup::"

      - name: ğŸ§ª Execute cowsay and save output
        run: |
          echo "::group::âœ¨ Running Cowsay"
          start_time=$(date +%s)
          
          cowsay -f kiss "hi how is this" > kiss.txt
          
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "ğŸ•’ Duration: ${duration}s"
          echo "::endgroup::"

      - name: ğŸ§¾ Debug reason input
        run: |
          echo "::group::ğŸ“ Reason Input"
          if [ -z "${{ github.event.inputs.reason }}" ]; then
            echo "Workflow reason: No manual reason given"
          else
            echo "Workflow reason: ${{ github.event.inputs.reason }}"
          fi
          echo "::endgroup::"

      - name: â˜ï¸ Upload kiss text file
        uses: actions/upload-artifact@v4
        with: 
          name: kiss-text-file
          path: kiss.txt

  test_job2:
    needs: build_job1
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Download kiss text file
        uses: actions/download-artifact@v4
        with: 
          name: kiss-text-file
          path: .

      - name: ğŸ” Test file exists
        run: |
          echo "::group:: Verifying Output"
          grep -i "hi how is this" kiss.txt
          echo "::endgroup::"

  deploy_job3:
    needs: test_job2
    runs-on: ubuntu-latest
    steps:
      - name:  Download kiss text file
        uses: actions/download-artifact@v4
        with: 
          name: kiss-text-file
          path: .

      - name:  Read file
        run: |
          echo "::group::ğŸ“– Displaying File"
          cat kiss.txt
          echo "::endgroup::"
